### ISSUE TITLE
Error: "The page has expired due to inactivity. Please refresh and try again."

### ISSUE THREAD

**Issue by jeremihz** [matthiku/cSpot#199] opened 2019-07-13 21:44 UTC
unable to register a user giving me th message The page has expired due to inactivity. 

Please refresh and try again......need some help

**Comment by matthiku** [comment] 2019-07-15 06:18
Ok. Can you give me some more details? What have you done so far? Did you fork the project on your own github?

**Comment by jeremihz** [comment] 2019-07-15 06:29
i kind off downloaded it and integrated it in my wamp
llocalhost......already set up its database and set up send mail
configuration...thats all

**Comment by matthiku** [comment] 2019-07-15 08:39
Did you follow all 8 steps in the installation instructions?
[https://github.com/matthiku/cSpot#installation](https://github.com/matthiku/cSpot#installation)
Have you got experience with Laravel?

**Comment by chris24walsh** [comment] 2020-03-20 19:06
I also see this issue. I'm using the new project Dockerfile to install and run via Docker, so the installation steps and issue are repeatable for anyone else. I'll investigate the issue once I get more familiar with the code.

**Comment by matthiku** [comment] 2020-03-23 21:07
OK, I found "a" solution, see:
https://stackoverflow.com/a/48938774/3202115
Not sure why, it could be the new syntax in the current Laravel version.

**Comment by matthiku** [comment] 2020-03-24 17:07
On further investigation and tests, I found also that this can be an issue with your browser's cached data! When I run this in an incognito Browser window, the issue is gone! 
@chris24walsh @jeremihz  Can you confirm this?

**Comment by chris24walsh** [comment] 2020-03-25 14:16
Hmm, running in incognito didn't resolve it until I ran the new code, then I tried the old code again on the side and didn't get the error!

**Comment by chris24walsh** [comment] 2020-03-25 14:20
Actually, I still see the error when I compare the old code to the new commit (where it is fixed). There are two different crsf tokens in the debug panel for the session and the request. Cached session token for the 'c-spot.app' domain?
![image](https://user-images.githubusercontent.com/10759472/77546433-2a388980-6eac-11ea-9c0c-d21b4de1384a.png)

**Comment by matthiku** [comment] 2020-03-25 16:21
This issue really confuses me! I have had the error again, cleared the cache and it worked. I really wonder what's going on. Probably my bad code .... ;)
Why don't you send me an email and we can arrange to have a screen sharing session where I walk you through the app and the code etc.?

**Comment by matthiku** [comment] 2020-04-29 09:47
Closing as it is not reproducible any more.

**Closed by matthiku** 2020-04-29 09:47 UTC
Labels: bug
